---

- name: kibana-install | Ensure kibana user is exist
  user: name={{ kibana_user }} group={{ kibana_group }}

- name: kibana-install | Ensure that kibana home is exist
  file: path={{kibana_home}}/src state=directory owner={{kibana_user}} group={{kibana_group}} mode=0755

- name: kibana-install | Ensure that kibana is downloaded
  get_url: url={{kibana_url}} dest={{kibana_home}}/src/kibana-{{kibana_version}}.tar.gz
  register: kibana_downloaded

- name: kibana-install | Ensure that kibana is extracted
  unarchive:
    copy=false
    dest={{kibana_home}}/src
    src={{kibana_home}}/src/kibana-{{kibana_version}}.tar.gz
  when: kibana_downloaded.changed

- name: kibana-install | Ensure that kibana is linked to current version
  file:
    src={{kibana_home}}/src/kibana-{{kibana_version}}-{{kibana_os_version}}
    dest={{kibana_home}}/www
    state=link
